
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123456
      POSTGRES_DB: fastapi_db
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: backend
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://admin:admin123456@db:5432/fastapi_db
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    ports:
      - "3000:3000"
