"""Remove status, priority, is_public from demos table

Revision ID: 307421c7762c
Revises: 810a0d09c2ff
Create Date: 2025-07-22 14:12:15.883403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '307421c7762c'
down_revision: Union[str, None] = '810a0d09c2ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('demos', 'status')
    op.drop_column('demos', 'priority')
    op.drop_column('demos', 'is_public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('demos', sa.Column('is_public', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('demos', sa.Column('priority', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('demos', sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
